# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5d8ebbaea83c07f738c48b39ce5dec0b773318ada541380514043b0c8b5d68d4d199844f5e1ef174b74dfb545e9515dacc1467c2abe48cffb15ddfbac18143a

test:
  secret_key_base: 60dbb964b8df00a3eee945bd78a20bb8b7b026cc927c62297685f8fac5b1ce1ecd9383a146e1c2dc2467eacc3c44b404eb73792eaeccfa5fdf8e45cb54f4e091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
